version: 1.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/hello-world
hooks:
  ApplicationStart:
    - location: /home/ec2-user/hello-world/start.sh
      timeout: 600
      runas: ec2-user